apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: sit-fe-admin-panel
  namespace: sit
  labels:
    app: sit-fe-admin-panel
=======
  name: dev-fe-admin-panel
  namespace: development
  labels:
    app: dev-fe-admin-panel
>>>>>>> 713d8841fd98d3af1a2942126b7500e6448b32e4
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: sit-fe-admin-panel
      tier: frontend
  template:
    metadata:
      labels:
        app: sit-fe-admin-panel
        tier: frontend
    spec:
      containers:
      - name: sit-fe-admin-panel
        image: registry-intl.ap-southeast-5.aliyuncs.com/uat-akses/sit-fe-admin-panel:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 45m
            memory: 225Mi
          requests:
            cpu: 30m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: sit-fe-adm-pnl
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always