apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-fe-admin-panel
  namespace: development
  labels:
    app: dev-fe-admin-panel
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: dev-fe-admin-panel
      tier: frontend
  template:
    metadata:
      labels:
        app: dev-fe-admin-panel
        tier: frontend
    spec:
      containers:
      - name: dev-fe-admin-panel
        image: registry-intl.ap-southeast-5.aliyuncs.com/dev-akses/dev-fe-admin-panel:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 45m
            memory: 225Mi
          requests:
            cpu: 30m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: dev-fe-adm-pnl
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always