apiVersion: v1
kind: Service
metadata:
  name: pprd-fe-admin-panel-svc
  namespace: preprod
  labels:
    app: pprd-fe-admin-panel
spec:
  ports:
  - name: http
    port: 80
    targetPort: 89
    protocol: TCP
  selector:
    app: pprd-fe-admin-panel
    tier: frontend
  type: LoadBalancer